name: Release Plugin

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Zip Release
      run: |
        cd dist
        zip -r ../logseq-hanzi-writer-integration.zip .
        cd ..
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: logseq-hanzi-writer-integration.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
